export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const CHANGE_DATE_FOCUS = 'CHANGE_DATE_FOCUS';
export const CHANGE_TASK_COMPLETION_STATUS = 'CHANGE_TASK_COMPLETION_STATUS';
